package com.shiro.dao.db.man;

import com.shiro.entity.BO.Man;
import org.springframework.stereotype.Component;

import java.util.List;
import java.util.Map;

/**
 * Created by wuyiming on 2017/9/18.
 */
@Component
public interface ManMapper {
    /**
     * This method was generated by MyBatis Generator.
     *
     * @mbggenerated Mon Sep 18 14:04:13 CST 2017
     */
    Man selectByPrimaryKey(String id);
    /**
     * This method was generated by MyBatis Generator.
     *
     * @mbggenerated Mon Sep 18 14:04:13 CST 2017
     */
    List<Man> selectByModel(Map model);
    /**
     * This method was generated by MyBatis Generator.
     *
     * @mbggenerated Mon Sep 18 14:04:13 CST 2017
     */
    List<Man> findAll();
    /**
     * This method was generated by MyBatis Generator.
     *
     * @mbggenerated Mon Sep 18 14:04:13 CST 2017
     */
    int deleteByPrimaryKey(String id);
    /**
     * This method was generated by MyBatis Generator.
     *
     * @mbggenerated Mon Sep 18 14:04:13 CST 2017
     */
    int deleteAll();
    /**
     * This method was generated by MyBatis Generator.
     *
     * @mbggenerated Mon Sep 18 14:04:13 CST 2017
     */
    int insert(Man record);
    /**
     * This method was generated by MyBatis Generator.
     *
     * @mbggenerated Mon Sep 18 14:04:13 CST 2017
     */
    int insertSelective(Man record);
    /**
     * This method was generated by MyBatis Generator.
     *
     * @mbggenerated Mon Sep 18 14:04:13 CST 2017
     */
    int updateByPrimaryKeySelective(Man record);
    /**
     * This method was generated by MyBatis Generator.
     *
     * @mbggenerated Mon Sep 18 14:04:13 CST 2017
     */
    int updateByPrimaryKey(Man record);
}
